### ISSUE TITLE
[BUG] - Getting null when clicking 'show' on an document

### ISSUE THREAD

**Issue by evelzi** [cars10/elasticvue#21] opened 2020-05-03 19:00 UTC
I am getting null instead of document.

![image](https://user-images.githubusercontent.com/52167266/80923005-28899d80-8d57-11ea-90d0-ce33c640831b.png)

I can see that the request made is: *http://myHost/myIndex/_doc/645550?format=json&type=myType*

The problem is that my document has { _type : "myType" } , and not _type equals to "_doc".
I mean, this query assumes that _type is _doc, but this is not true in my case.

It would be great if you can fix it!

Thanks in advance.

**Comment by cars10** [comment] 2020-05-04 06:15
Hi, please use the provided issue template when opening an issue. Can you at least fill out the following information:

**Environment (please include the following information):**
* Operating system:
* Browser + version:
* Elasticvue version:
* How are you running elasticvue? (docker, browser extension, web app):

**Comment by benhackley** [comment] 2020-05-08 18:48
Also experiencing this issue. 

- **OS**: Windows 10 Pro
     - **Version**: 1809
     - **Build**: 17763.1158

- **Browser**: Chrome v81.0.4044.138 

- **Elasticvue version**: using Docker image cars10/elasticvue:latest

- Running in Docker. 

Seeing the GET request to _http://myHost/myIndex/_doc/myDocId?format=json&type=myType_ return 404. 

![nullDoc](https://user-images.githubusercontent.com/8715789/81438384-afb18980-913a-11ea-96eb-0801cffbe1a0.PNG)

**Comment by cars10** [comment] 2020-05-09 16:16
What version of elasticsearch are you using?

**Comment by benhackley** [comment] 2020-05-09 16:24
I am using v0.21.0, [this image](https://hub.docker.com/layers/cars10/elasticvue/v0.21.0/images/sha256-390cb372141c5a4f057cb192c5de923c2be74d704188f825988196019cdcd967?context=explore).

**Comment by cars10** [comment] 2020-05-09 16:24
elastic**search** version please :)

**Comment by benhackley** [comment] 2020-05-09 16:26
Oops! Sorry! Elasticsearch version 6.4.0.

**Comment by cars10** [comment] 2020-05-11 11:26
Thanks! I can reproduce the issue with non standard types. Mapping types are deprecated as of elasticsearch 7, but i will try to fix this issue.

**Comment by benhackley** [comment] 2020-05-11 11:59
Awesome! Thanks, much appreciated.

**Comment by cars10** [comment] 2020-05-18 15:31
Fixed via cd8741d4001c3986a95378f655dbd1a23bb4ade9 for elasticvue version 0.22.0, forgot to mention it in the changelog. You can already try in the hosted version and the docker image.
The browser extensions still take some days until they are published :)

**Closed by cars10** 2020-05-18 15:31 UTC
Labels: unconfirmed

**Comment by benhackley** [comment] 2020-05-18 15:41
Thanks again for the quick fix. Pulled v0.22.0 docker image and that is working for me!

**Comment by cars10** [comment] 2020-05-18 15:43
Awesome! Thanks for the quick feedback.

I was a bit worried with this version because i had to remove the official elasticsearch lib. Everything is done manually now, please open an issue if you do have any problems :)
