### ISSUE TITLE
[BUG] - Sending REST queries with GET leads to an elasticsearch exception

### ISSUE THREAD

**Issue by daniellienert** [cars10/elasticvue#26] opened 2020-06-15 09:25 UTC
**Description**
When sending a simple query via a get request, an elasticsearch exception is returned.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Get to the REST tab
3. Select the GET method and target the _search endpoint

**Screenshots**
With GET:
![image](https://user-images.githubusercontent.com/642226/84640687-50dded80-aefa-11ea-9811-bb26a323ab13.png)

With POST
![image](https://user-images.githubusercontent.com/642226/84640734-60f5cd00-aefa-11ea-81d3-e4a9d3bd33a6.png)

**Environment (please include the following information):**
* Elasticsearch version: 7.7.0
* Operating system: MacOS / Docker
* Browser + version: Chrome Version 83.0.4103.97 (Offizieller Build) (64-Bit)
* Elasticvue version: 0.22.0
* How are you running elasticvue? browser extension

**Additional context**
Anything else?

Yes, **thanks a bunch for this awesome project!!** After using Head for years and nowadays Kibana instances, this UI is aboslutely awesome to debug queries in a lightweight way!

**Comment by cars10** [comment] 2020-06-15 11:34
Hi, thanks for contributing to elasticvue :)

This error is a technical limitation: javascript fetch (this is used under the hood) does not allow users to send a request body via get. Whenever you send data to a server it should usually be a POST, PUT or PATCH. As far as i know, elasticsearch is the only software that even accepts a request body via GET.

I will prevent the error from occuring by disabling the "Request body" field when GET is set as HTTP method. 

It will look like this when GET is selected:

![image](https://user-images.githubusercontent.com/4118628/84652944-c488f600-af0c-11ea-8001-14863ceec2ed.png)

And like this when POST is selected (unchanged)
![image](https://user-images.githubusercontent.com/4118628/84653001-da96b680-af0c-11ea-8554-9e25af8127af.png)

Does this work for you?

**Comment by daniellienert** [comment] 2020-06-15 17:00
Thanks @cars10, looks great and using POST is perfectly fine! 
Seemed the first level of the JSON object was kind of sent, which lead to a confusing error.

**Comment by cars10** [comment] 2020-06-22 15:31
Fixed in `0.23.0`. Thanks again!

**Closed by cars10** 2020-06-22 15:31 UTC
Labels: bug

**Comment by bm-stschneider** [comment] 2020-09-23 10:28
@cars10 With older versions the opposite is the case. You have to send a GET with a JSON body in order to work. Can you enable that again for search and rest since otherwise I keep running into 403 Forbidden for POST requests.

**Comment by cars10** [comment] 2022-08-19 07:16
> @cars10 With older versions the opposite is the case. You have to send a GET with a JSON body in order to work. Can you enable that again for search and rest since otherwise I keep running into 403 Forbidden for POST requests. Online with the browser extension and an instance in docker with port forwarding.

I cannot reproduce this, can you please give me more details on this? Elasticsearch has supported POST for requests like search for a very long time. A 403 forbidden might also be related to your environment and not elasticsearch itself.

![image](https://user-images.githubusercontent.com/4118628/185564731-a9fb7260-1e9f-4509-8421-70e60fb26fab.png)
![image](https://user-images.githubusercontent.com/4118628/185564792-5fa19148-0622-4e0b-acce-25aa0f87b2c2.png)

Tested with the official docker image:

```
docker run --rm --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:5.6.16
```
