### ISSUE TITLE
[FEAT] Support for AWS IAM Authentication

### ISSUE THREAD

**Issue by gw-bcharboneau** [cars10/elasticvue#207] opened 2024-02-14 17:41 UTC
**Description**
AWS utilizes IAM Access Key for authentication, if possible it would be nice to offer it as one of the authentication methods.

Inclusion of the optional Session Token would also be helpful for users that utilize federated access

**The feature is similar to..**
Does the feature exist in a similar tool?
[Postman](https://www.postman.com)
![image](https://github.com/cars10/elasticvue/assets/58750574/dd52c9b4-975e-41b6-85e1-8d2cde5d1c4a)

**Additional context**
IAM Auth will help ensure security as AWS starts to implement Security changes which may require IAM Auth to be enabled
Feel free to reach out to me if you needs someone to help with pre-release testing for this feature.

**Comment by cars10** [comment] 2024-02-14 18:12
Duplicate of #148 . I currently don't have access to an example project to test this.

**Closed by cars10** 2024-02-14 18:12 UTC
Labels: feature

**Comment by cars10** [comment] 2025-06-22 12:30
Added in 1.8.0.
