### ISSUE TITLE
[BUG] - Chinese input error in the rest box

### ISSUE THREAD

**Issue by YuLiGod** [cars10/elasticvue#178] opened 2023-12-26 02:34 UTC
非常高兴看到了你们的新版本,现在可以推荐更多的dsl提示,还可以对rest进行保存；
但是，在rest的文本编辑框内输入中文的过程中，会被自动打断和跳转到文本编辑的开头，能否解决下这个问题，对涉及中文的存储很不友好
<img width="716" alt="image" src="https://github.com/cars10/elasticvue/assets/76502772/4a0d0400-0e81-4488-84bf-557c3561dbad">

**Comment by YuLiGod** [comment] 2023-12-26 02:34
I am very pleased to see your new version. Now I can recommend more DSL prompts and also save the rest;

However, during the process of inputting Chinese into the text editing box in rest, it will be automatically interrupted and redirected to the beginning of the text editing. Can you solve this problem? It is very unfriendly to storage involving Chinese

**Comment by cars10** [comment] 2023-12-31 16:36
I cannot reproduce this issue, but i believe it might be a duplicate of #180. Please try with version `1.0.1` and report back if the issue persists :)

**Closed by cars10** 2023-12-31 16:36 UTC
Labels: unconfirmed
