### ISSUE TITLE
[BUG] - Can't launch linux app

### ISSUE THREAD

**Issue by javier-de-juan** [cars10/elasticvue#127] opened 2022-11-28 11:34 UTC
**Description**
When I try to launch the linux app, it fails. Message received is: `elasticvue: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`. I've tried to install that dependency but I couldn't easily. I don't have any problem to connect with the Firefox extension.
 
**Steps To Reproduce**
List the steps to reproduce your problem:
1. Download elasticvue
2. Install it
3. Try to launch

**Environment:**
* Elasticsearch version:  7.1.0
* Operating system: Ubuntu 22.10 (Also happened with 20.04)
* Elasticvue version: 0.44 (also happened with previous)
* How are you running elasticvue? (Linux app):

**Comment by cars10** [comment] 2022-11-28 11:36
Which version do you use? Binary, dep package, appimage?

**Comment by javier-de-juan** [comment] 2022-11-29 14:55
I'm using .deb package

**Comment by cars10** [comment] 2022-11-29 16:02
Thanks! I will try to reproduce the issue.

**Comment by cars10** [comment] 2023-03-05 10:49
Seems to be a build issue, i will try to switch to rustls

**Comment by cars10** [comment] 2023-06-25 13:30
This will be fixed in the upcoming 1.0 beta.

**Closed by cars10** 2023-06-25 13:30 UTC
Labels: bug
