### ISSUE TITLE
[BUG] - Elasticvue doesn't show all templates

### ISSUE THREAD

**Issue by aidin-gh** [cars10/elasticvue#239] opened 2024-06-25 01:33 UTC
**Description**

I have a few templates on my cluster. I can see them by calling `_index_templates` API directly, but the app doesn't show them. I tried it on a new single-node cluster on my local machine, and the result was the same.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Run Elastic Search locally using docker.
2. Put an `_index_template`. For example I tried this:

```
curl -X PUT -H 'Content-Type: application/json' 'localhost:9200/_index_template/bugreport_test1' -d '{
  "index_patterns": ["bug_test_*"],
    "template": {
      "settings": {
        "number_of_shards": 1
      },
     "mappings": {
      "properties": {
        "date": {
          "format": "yyyy-MM-dd",
          "type": "date"
        }
      }
    }
  }
}'
```

3. Open Elasticvue and go to the `Index Templates`. The template is not there.

I tried disconnecting and re-connecting, and resetting the app. But templates didn't appear.

**Screenshots**

![Screenshot_20240625_133032](https://github.com/cars10/elasticvue/assets/38443968/9f8cf256-6283-49e6-940c-76f8175d2c11)
![Screenshot_20240625_132948](https://github.com/cars10/elasticvue/assets/38443968/8da41cbc-b38c-4b5a-a05d-ed35d39b57f9)

**Environment (please include the following information):**
* Elasticsearch version: 8.14.1
* Operating system: Ubuntu 24.04
* Browser + version:
* Elasticvue version: 1.0.8-stable
* How are you running elasticvue? (docker, browser extension, web app): Linux AppImage

**Comment by cars10** [comment] 2024-07-01 07:00
The API you are referring to is the legacy API. It seems like your templates are not migrated yet, see the info box at the top here: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-template-v1.html

This is also a duplicate of #170

**Closed by cars10** 2024-07-01 07:00 UTC
Labels: unconfirmed

**Comment by aidin-gh** [comment] 2024-07-01 20:21
Hi @cars10,
Thanks for looking into this!

I'm using the new API. The legacy API is `/_template/`, but as you see in the `curl` command and the screenshot, I'm using the new `_index_template` API.

**Comment by aidin-gh** [comment] 2024-07-01 20:50
I installed the Firefox Addon, and I can see that it's calling the legacy URI.

Please let me know if I can collect any info about this issue that helps you identify it.

![Screenshot_20240702_084831](https://github.com/cars10/elasticvue/assets/38443968/e25e857a-ef3a-488c-94fa-bb9844e03eae)
