### ISSUE TITLE
[BUG] - Open document with "_routing" from "Search" panel

### ISSUE THREAD

**Issue by Eliak** [cars10/elasticvue#63] opened 2021-08-10 09:30 UTC
**Description**
I have documents with parent-child relation in my index. And my index have multiple shards. I see child documents in the list on *Search* panel. But i`ve got an error when click on it.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on *Search*
3. Put query *_exists_:_routing* into *Search* query editor.
4. Click on *Search* button.
5. Click on any record from resultset.

**Screenshots**
![image](https://user-images.githubusercontent.com/3325838/128842947-8520a747-fe5a-4950-a64a-7f52e2739a9a.png)

**Comment by cars10** [comment] 2021-08-10 10:53
Hey, thanks for using elasticvue :)

So far i cant reproduce this issue. Are you sure that the documents/index you are trying to access still exists? Maybe they where deleted after your search? Can you provide example data?

**Comment by Eliak** [comment] 2021-08-10 14:03
Hello, thank you for elasticvue, this is a great tool, I love it.

Yes, indices and documents are exists and *search* button works great.

There are some examples in elastic documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html.

The problem is exactly with parent-child relations. Elastic always store child document on the same shard with parent. So to use GET API to fetch child document we need to add parent`s document id to request. Elastic gives it in *_routing* filed of hit. 
This is one more documentation article on GET API https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#get-routing

**Comment by cars10** [comment] 2021-08-11 18:58
Thanks! Fixed in `0.36.0`

**Closed by cars10** 2021-08-11 18:58 UTC
Labels: unconfirmed
