### ISSUE TITLE
Got 'ERR_TOO_MANY_REDIRECTS' after refreshing extension page

### ISSUE THREAD

**Issue by foqq** [cars10/elasticvue#2] opened 2019-04-12 12:02 UTC
`chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/index.html?route=/`

This page isn’t working hkedbapjpblbodpgbajblpnlpenaebaa redirected you too many times.

Try clearing your cookies.

**ERR_TOO_MANY_REDIRECTS**

**Comment by cars10** [comment] 2019-04-12 12:11
Hi, i cannot reproduce the issue. Can you please tell me the following:
* Browser version
* Elasticvue version (see the footer or visit [chrome://extensions/](chrome://extensions/) )
* On what page where you when you tried to refresh?

**Comment by foqq** [comment] 2019-04-15 02:09
Hi, thanks for reply!

Following is my environment:
OS: macOS mojave 10.14.4
Browser: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Extension: Elasticvue 0.9.2 (Installed from Google Web Store)
Pages: /, /nodes, /indices, /search, ... (all the same)

**Comment by cars10** [comment] 2019-04-15 12:53
Thanks for the update. I could not reproduce the issue on linux but i have the same problem on macos and windows. Working on it!

**Comment by cars10** [comment] 2019-04-15 13:55
fixed via 6cfb3aa08d342606214a74e0ad56ca448810ddb5 .

The issue should be fixed, thanks for reporting. You can update the extension on chrome://extensions

**Closed by cars10** 2019-04-15 13:55 UTC
Labels: bug

**Comment by foqq** [comment] 2019-04-16 02:00
Great job! Thanks for the quick fix.

The latest version in Google Web Store works properly.

**Comment by foqq** [comment] 2019-04-16 02:10
Sorry to boring you again. The web version seems to have similar issue on URL routing. Would you please take a look at it?

**Comment by cars10** [comment] 2019-04-16 06:27
Hm, i updated the web version yesterday. Can you please clear your cache and try again? Works for me on linux&windows, no macos here right now.

**Comment by foqq** [comment] 2019-04-16 07:52
I tried v0.10.0. It works fine when running locally with 'yarn serve', however runs into error when deployed and served with nginx.

**Comment by cars10** [comment] 2019-04-16 07:58
Hm, can you please try on [http://app.elasticvue.com/](http://app.elasticvue.com/) ? If it works there then it is an error in your nginx config, sounds like you might be missing the block to route all requests to index.html


    location / {
        try_files $uri $uri/ /index.html?$args;
    }

**Comment by foqq** [comment] 2019-04-16 08:26
Thanks so much. I did miss the try_files line.

**Comment by cars10** [comment] 2019-04-16 08:28
Great! Let me know if you have any other issues.
