### ISSUE TITLE
[BUG] Missing table headers

### ISSUE THREAD

**Issue by georgeyeint** [cars10/elasticvue#6] opened 2019-08-29 08:00 UTC
Hi, Carsten,

**Description**
not showing table headers at search menu (/index.html#/search)
In DOM structure they are empty.
Tried "Sticky table header" on and off, no result.

**Steps To Reproduce**
1. Open elasticvue
2. Click search menu
3. empty :-)

**Screenshots**
![esvue](https://user-images.githubusercontent.com/52407577/63921162-fcd94980-ca4a-11e9-951d-3d7ed1272c73.png)

**Environment (please include the following information):**
* ElasticSearch 7
* Ubuntu 18.04.3 server, client Windows 10 pro
* on client Google Chrome. 76.0.3809.100 (64 bit)
* on client Elasticvue 0.11.0
* on client chrome extension

**Additional context**
thanks for your work

**Comment by cars10** [comment] 2019-08-29 08:28
Hi, thank you for your bug report and sorry that you encountered this. Sadly i cannot simply reproduce the issue so i have a few more questions for you:

* Do you see any javascript errors in the browser console?
* Is the issue fixed by clicking on "Disconnect and reset" in the footer? This will reset all your saved filters and you have to reconnect to your cluster.
* Do you have any special characters in the names of your index mappings, for example mappings in cyrillic?

Thanks!

**Comment by georgeyeint** [comment] 2019-08-29 09:15
JS Console: Failed to load resource: the server responded with a status of 404 (Not Found)  http://192.168.34.56:9200/_cat/indices/c_?format=json&h=index

"Disconnect and reset" fixed the issue!!!

Title names in cyrillic - yes. for example "Внутренний диаметр шланга"

May be usefull info, i have 500 indexes with 100-600 columns in each. 
In general i try to import 1M rows with 6000 columns.

**Comment by cars10** [comment] 2019-08-29 16:58
Wow, this is a huge amount of data. I have no idea how well elasticvue will handle this =O

Thank you for you feedback, i am glad that it works again. I will try to reproduce the issue.

**Comment by cars10** [comment] 2019-11-12 13:05
I will close this issue for now because i still cannot reproduce it. Feel free to comment or reopen if you encounter the issue again :)

**Closed by cars10** 2019-11-12 13:05 UTC
Labels: bug, unconfirmed
